---
id: gantt-settings
name:
  ru: Настройки диаграмм Ганта
  en: Gantt chart settings
parentRef: emodel/type@ecos-vcs-object
formRef: uiserv/form@DEFAULT_FORM
journalRef: uiserv/journal@gantt-settings-journal
system: true
defaultStatus: created
inheritForm: false
defaultCreateVariant: false
storageType: ECOS_MODEL

model:
  statuses:
    - id: created
      name:
        en: Created
        ru: Создано
    - id: EMPTY
  roles:
    - id: EVERYONE
    - id: creator
      attributes:
        - _creator
    - id: administrators
      name:
        ru: Администратор
        en: Administrator
      assignees:
        - GROUP_ECOS_ADMINISTRATORS
  attributes:
    - id: name
      name:
        en: Name
        ru: Наименование
      type: MLTEXT
    - id: dataType
      name:
        en: Data type
        ru: Тип данных
      type: OPTIONS
      mandatory: true
      config:
        values:
          - value: STANDALONE
            label:
              en: Standalone (diagram-only)
              ru: Автономный (только диаграмма)
          - value: LINKED
            label:
              en: Linked (business entities)
              ru: Связанный (бизнес-сущности)
    - id: linkedWithType
      name:
        en: Linked with type
        ru: Связан с типом
      type: ASSOC
    - id: linkedWithRef
      name:
        en: Link with document
        ru: Связь с документом
      type: ASSOC
    - id: dataSourceId
      name:
        en: SourceId of data source
        ru: SourceId источника данных
    - id: manualDataSourceId
      name:
        en: SourceId of data source (manual input)
        ru: SourceId источника данных (ручной ввод)
      type: TEXT
    - id: data
      name:
        en: Data
        ru: Данные
      type: ASSOC
      multiple: false
      config:
        typeRef: emodel/type@gantt-data
